// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_44vyUnOU9__9WCuG0sxyef58sOQn5N8',
    appId: '1:706089900083:web:58b365863d13d2a76b6b46',
    messagingSenderId: '706089900083',
    projectId: 'moneyminder-70520',
    authDomain: 'moneyminder-70520.firebaseapp.com',
    storageBucket: 'moneyminder-70520.appspot.com',
    measurementId: 'G-RTWL018SMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDOPAWGJxVO3I_jrAo2XawxK8et_2N0M',
    appId: '1:706089900083:android:c9d795441a366d4d6b6b46',
    messagingSenderId: '706089900083',
    projectId: 'moneyminder-70520',
    storageBucket: 'moneyminder-70520.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqhUxy-DFWcuXCLyS04WrElrsy1i1GIxI',
    appId: '1:706089900083:ios:5a42b0231ee778e26b6b46',
    messagingSenderId: '706089900083',
    projectId: 'moneyminder-70520',
    storageBucket: 'moneyminder-70520.appspot.com',
    iosBundleId: 'com.example.finkuCloneSlicing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqhUxy-DFWcuXCLyS04WrElrsy1i1GIxI',
    appId: '1:706089900083:ios:a8035feb2997efed6b6b46',
    messagingSenderId: '706089900083',
    projectId: 'moneyminder-70520',
    storageBucket: 'moneyminder-70520.appspot.com',
    iosBundleId: 'com.moneyminder.app',
  );
}
